version: "3"
services:
    mysql:
        image: "myapp/mysql5.7:0.0.1"
        ports:
            - "3316:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: "123456"
        volumes:
            - "./data/mysql/3306/:/var/lib/mysql/"
            - "/etc/localtime:/etc/localtime:ro"
        networks:
            - webnet
    redis:
        image: "myapp/redis3.2:0.0.1"
        ports:
            - "6379:6379"
        volumes:
            - "./data/redis/6379/:/data/"
            - "/etc/localtime:/etc/localtime:ro"
        deploy:
            placement:
                constraints: [node.role == manager]
        command: redis-server --appendonly yes
        networks:
            - webnet
    php7:
        image: "myapp/php7.0-fpm:0.0.1"
        ports:
            - "9009:9000"
        volumes:
        #    - "./config/php7/php-fpm.d/:/usr/local/etc/php-fpm.d/"
        #    - "./config/php7/conf.d/:/usr/local/etc/php/conf.d/"
            - "./case/:/opt/case/"
        #    - "./logs/php7/:/var/logs/php/"
            - "/etc/localtime:/etc/localtime:ro"
        networks:
            - webnet
    nginx:
        image: "myapp/nginx1.14:0.0.1"
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - "./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
            - "./config/nginx/conf.d/:/etc/nginx/conf.d/"
            - "./logs/nginx/:/opt/logs/nginx/"
            - "./case/:/opt/case/"
            - "/etc/localtime:/etc/localtime:ro"
        networks:
            - webnet
networks:
    webnet:
